module.exports = {
    content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
    darkMode: 'class',
    theme: {
        screens: {
            xs: '320px',
            sm: '480px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1440px',
            '3xl': '1920px',
            '4k': '2560px',
        },
        extend: {
            colors: {
                bg: 'var(--bg)',
                's0': 'var(--s0)',
                's1': 'var(--s1)',
                's2': 'var(--s2)',
                's3': 'var(--s3)',
                's4': 'var(--s4)',
                's5': 'var(--s5)',
                bd: 'var(--bd)',
                bd1: 'var(--bd1)',
                bd2: 'var(--bd2)',
                bd3: 'var(--bd3)',
                't0': 'var(--t0)',
                't1': 'var(--t1)',
                't2': 'var(--t2)',
                't3': 'var(--t3)',
                cy: 'var(--cy)',
                cy1: 'var(--cy1)',
                cy2: 'var(--cy2)',
                cy3: 'var(--cy3)',
                em: 'var(--em)',
                em1: 'var(--em1)',
                em2: 'var(--em2)',
                em3: 'var(--em3)',
                am: 'var(--am)',
                am1: 'var(--am1)',
                am2: 'var(--am2)',
                am3: 'var(--am3)',
                rd: 'var(--rd)',
                rd1: 'var(--rd1)',
                rd2: 'var(--rd2)',
                rd3: 'var(--rd3)',
                vl: 'var(--vl)',
                vl1: 'var(--vl1)',
                vl2: 'var(--vl2)',
                vl3: 'var(--vl3)',
                bl: 'var(--bl)',
                nv: 'var(--nv)',
                gs: 'var(--gs)',
                go: 'var(--go)',
                sl: 'var(--sl)',
                ice: 'var(--ice)',
            },
            fontFamily: {
                display: ['Playfair Display', 'serif'],
                mono: ['JetBrains Mono', 'monospace'],
                body: ['Plus Jakarta Sans', 'sans-serif'],
            },
            fontWeight: {
                900: '900',  /* fixes font-900 in typographyClasses */
            },
            fontSize: {
                xs: ['12px', { lineHeight: '16px', letterSpacing: '-0.01em' }],
                sm: ['13px', { lineHeight: '18px', letterSpacing: '-0.005em' }],
                base: ['15px', { lineHeight: '24px', letterSpacing: '0' }],
                lg: ['17px', { lineHeight: '26px', letterSpacing: '0.005em' }],
                xl: ['20px', { lineHeight: '28px', letterSpacing: '0.01em' }],
            },
            spacing: {
                safe: 'env(safe-area-inset-bottom)',
            },
            animation: {
                shimmer: 'shimmer 2s infinite',
                pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'fade-in': 'fadeIn 0.3s ease-out',
                'slide-up': 'slideUp 0.3s ease-out',
                'slide-down': 'slideDown 0.3s ease-out',
            },
            keyframes: {
                shimmer: {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%': { transform: 'translateY(16px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideDown: {
                    '0%': { transform: 'translateY(-16px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
            },
            backdropBlur: {
                xs: '2px',
                sm: '4px',
            },
        },
    },
    plugins: [],
}

